/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rolandomagico_jniresourceloader_ResourceLoader */

#ifndef _Included_rolandomagico_jniresourceloader_ResourceLoader
#define _Included_rolandomagico_jniresourceloader_ResourceLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rolandomagico_jniresourceloader_ResourceLoader
 * Method:    getTranslatedString
 * Signature: (Ljava/lang/String;JJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rolandomagico_jniresourceloader_ResourceLoader_getTranslatedString
  (JNIEnv *, jclass, jstring, jlong, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
