/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rolandomagico_jniresourceloader_ResourceLoader */

#ifndef _Included_rolandomagico_jniresourceloader_ResourceLoader
#define _Included_rolandomagico_jniresourceloader_ResourceLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rolandomagico_jniresourceloader_ResourceLoader
 * Method:    getStringResource
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rolandomagico_jniresourceloader_ResourceLoader_getStringResource
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
